// @generated by protoc-gen-connect-es v0.9.0 with parameter "target=ts"
// @generated from file proto/service.proto (package uniswap.info.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PoolDayDatasRequest, PoolDayDatasResponse } from "./service_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service uniswap.info.v1.UniswapInfo
 */
export const UniswapInfo = {
  typeName: "uniswap.info.v1.UniswapInfo",
  methods: {
    /**
     * @generated from rpc uniswap.info.v1.UniswapInfo.PoolDayDatas
     */
    poolDayDatas: {
      name: "PoolDayDatas",
      I: PoolDayDatasRequest,
      O: PoolDayDatasResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

